# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ppsdtool_gui.ui'
#
# Created: Tue Jun 28 11:23:53 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(742, 685)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.group0 = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group0.sizePolicy().hasHeightForWidth())
        self.group0.setSizePolicy(sizePolicy)
        self.group0.setMinimumSize(QtCore.QSize(150, 100))
        self.group0.setObjectName(_fromUtf8("group0"))
        self.t1 = QtGui.QLineEdit(self.group0)
        self.t1.setGeometry(QtCore.QRect(210, 20, 81, 26))
        self.t1.setObjectName(_fromUtf8("t1"))
        self.t2 = QtGui.QLineEdit(self.group0)
        self.t2.setGeometry(QtCore.QRect(180, 50, 81, 26))
        self.t2.setObjectName(_fromUtf8("t2"))
        self.project = QtGui.QLineEdit(self.group0)
        self.project.setEnabled(True)
        self.project.setGeometry(QtCore.QRect(20, 10, 113, 26))
        self.project.setObjectName(_fromUtf8("project"))
        self.station = QtGui.QLineEdit(self.group0)
        self.station.setGeometry(QtCore.QRect(0, 40, 71, 26))
        self.station.setObjectName(_fromUtf8("station"))
        self.component = QtGui.QLineEdit(self.group0)
        self.component.setGeometry(QtCore.QRect(90, 60, 41, 26))
        self.component.setObjectName(_fromUtf8("component"))
        self.gridLayout.addWidget(self.group0, 1, 0, 1, 1)
        self.pbar = QtGui.QProgressBar(self.centralwidget)
        self.pbar.setProperty(_fromUtf8("value"), 0)
        self.pbar.setTextVisible(True)
        self.pbar.setObjectName(_fromUtf8("pbar"))
        self.gridLayout.addWidget(self.pbar, 2, 0, 1, 3)
        self.group1 = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group1.sizePolicy().hasHeightForWidth())
        self.group1.setSizePolicy(sizePolicy)
        self.group1.setObjectName(_fromUtf8("group1"))
        self.button = QtGui.QPushButton(self.group1)
        self.button.setGeometry(QtCore.QRect(30, 20, 61, 25))
        self.button.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.button.setObjectName(_fromUtf8("button"))
        self.push_open = QtGui.QPushButton(self.group1)
        self.push_open.setGeometry(QtCore.QRect(220, 20, 100, 25))
        self.push_open.setObjectName(_fromUtf8("push_open"))
        self.push_save = QtGui.QPushButton(self.group1)
        self.push_save.setGeometry(QtCore.QRect(220, 60, 100, 25))
        self.push_save.setObjectName(_fromUtf8("push_save"))
        self.push_plot = QtGui.QPushButton(self.group1)
        self.push_plot.setGeometry(QtCore.QRect(40, 60, 61, 25))
        self.push_plot.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.push_plot.setObjectName(_fromUtf8("push_plot"))
        self.check_plot1 = QtGui.QCheckBox(self.group1)
        self.check_plot1.setGeometry(QtCore.QRect(130, 10, 21, 23))
        self.check_plot1.setText(_fromUtf8(""))
        self.check_plot1.setChecked(True)
        self.check_plot1.setObjectName(_fromUtf8("check_plot1"))
        self.check_plot2 = QtGui.QCheckBox(self.group1)
        self.check_plot2.setGeometry(QtCore.QRect(160, 30, 21, 23))
        self.check_plot2.setText(_fromUtf8(""))
        self.check_plot2.setChecked(True)
        self.check_plot2.setObjectName(_fromUtf8("check_plot2"))
        self.check_plot3 = QtGui.QCheckBox(self.group1)
        self.check_plot3.setGeometry(QtCore.QRect(140, 50, 21, 23))
        self.check_plot3.setText(_fromUtf8(""))
        self.check_plot3.setChecked(True)
        self.check_plot3.setObjectName(_fromUtf8("check_plot3"))
        self.check_plot4 = QtGui.QCheckBox(self.group1)
        self.check_plot4.setGeometry(QtCore.QRect(180, 60, 21, 23))
        self.check_plot4.setText(_fromUtf8(""))
        self.check_plot4.setChecked(True)
        self.check_plot4.setObjectName(_fromUtf8("check_plot4"))
        self.gridLayout.addWidget(self.group1, 1, 2, 1, 1)
        self.canv = MPLWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canv.sizePolicy().hasHeightForWidth())
        self.canv.setSizePolicy(sizePolicy)
        self.canv.setAutoFillBackground(True)
        self.canv.setObjectName(_fromUtf8("canv"))
        self.gridLayout.addWidget(self.canv, 0, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 742, 22))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuEnable = QtGui.QMenu(self.menuBar)
        self.menuEnable.setObjectName(_fromUtf8("menuEnable"))
        MainWindow.setMenuBar(self.menuBar)
        self.actionAdd_Console = QtGui.QAction(MainWindow)
        self.actionAdd_Console.setObjectName(_fromUtf8("actionAdd_Console"))
        self.actionSave_Data = QtGui.QAction(MainWindow)
        self.actionSave_Data.setObjectName(_fromUtf8("actionSave_Data"))
        self.actionLogging_to_File = QtGui.QAction(MainWindow)
        self.actionLogging_to_File.setObjectName(_fromUtf8("actionLogging_to_File"))
        self.actionLogging_Window = QtGui.QAction(MainWindow)
        self.actionLogging_Window.setObjectName(_fromUtf8("actionLogging_Window"))
        self.actionStart_IPython = QtGui.QAction(MainWindow)
        self.actionStart_IPython.setObjectName(_fromUtf8("actionStart_IPython"))
        self.menuEnable.addAction(self.actionAdd_Console)
        self.menuEnable.addAction(self.actionStart_IPython)
        self.menuEnable.addAction(self.actionLogging_to_File)
        self.menuEnable.addAction(self.actionLogging_Window)
        self.menuBar.addAction(self.menuEnable.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.button, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.project.setEnabled)
        QtCore.QObject.connect(self.button, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.station.setEnabled)
        QtCore.QObject.connect(self.button, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.component.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.project, self.station)
        MainWindow.setTabOrder(self.station, self.component)
        MainWindow.setTabOrder(self.component, self.t1)
        MainWindow.setTabOrder(self.t1, self.t2)
        MainWindow.setTabOrder(self.t2, self.button)
        MainWindow.setTabOrder(self.button, self.push_plot)
        MainWindow.setTabOrder(self.push_plot, self.push_open)
        MainWindow.setTabOrder(self.push_open, self.push_save)
        MainWindow.setTabOrder(self.push_save, self.check_plot1)
        MainWindow.setTabOrder(self.check_plot1, self.check_plot2)
        MainWindow.setTabOrder(self.check_plot2, self.check_plot3)
        MainWindow.setTabOrder(self.check_plot3, self.check_plot4)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.group0.setTitle(QtGui.QApplication.translate("MainWindow", "Data", None, QtGui.QApplication.UnicodeUTF8))
        self.t1.setStatusTip(QtGui.QApplication.translate("MainWindow", "start day to add data", None, QtGui.QApplication.UnicodeUTF8))
        self.t1.setText(QtGui.QApplication.translate("MainWindow", "2000-01-01", None, QtGui.QApplication.UnicodeUTF8))
        self.t2.setStatusTip(QtGui.QApplication.translate("MainWindow", "end day to add data", None, QtGui.QApplication.UnicodeUTF8))
        self.t2.setText(QtGui.QApplication.translate("MainWindow", "2000-01-03", None, QtGui.QApplication.UnicodeUTF8))
        self.project.setStatusTip(QtGui.QApplication.translate("MainWindow", "Data class", None, QtGui.QApplication.UnicodeUTF8))
        self.project.setText(QtGui.QApplication.translate("MainWindow", "Parkfield", None, QtGui.QApplication.UnicodeUTF8))
        self.station.setStatusTip(QtGui.QApplication.translate("MainWindow", "station", None, QtGui.QApplication.UnicodeUTF8))
        self.station.setText(QtGui.QApplication.translate("MainWindow", "PKD", None, QtGui.QApplication.UnicodeUTF8))
        self.component.setStatusTip(QtGui.QApplication.translate("MainWindow", "component", None, QtGui.QApplication.UnicodeUTF8))
        self.component.setText(QtGui.QApplication.translate("MainWindow", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.group1.setTitle(QtGui.QApplication.translate("MainWindow", "PPSD", None, QtGui.QApplication.UnicodeUTF8))
        self.button.setStatusTip(QtGui.QApplication.translate("MainWindow", "Create new PPSD object / add data to existing PPSD object", None, QtGui.QApplication.UnicodeUTF8))
        self.button.setText(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.push_open.setStatusTip(QtGui.QApplication.translate("MainWindow", "Open PPSD", None, QtGui.QApplication.UnicodeUTF8))
        self.push_open.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.push_save.setStatusTip(QtGui.QApplication.translate("MainWindow", "Save PPSD", None, QtGui.QApplication.UnicodeUTF8))
        self.push_save.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.push_plot.setStatusTip(QtGui.QApplication.translate("MainWindow", "Plot PPSD", None, QtGui.QApplication.UnicodeUTF8))
        self.push_plot.setText(QtGui.QApplication.translate("MainWindow", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.check_plot1.setStatusTip(QtGui.QApplication.translate("MainWindow", "show coverage", None, QtGui.QApplication.UnicodeUTF8))
        self.check_plot2.setStatusTip(QtGui.QApplication.translate("MainWindow", "show histogram", None, QtGui.QApplication.UnicodeUTF8))
        self.check_plot3.setStatusTip(QtGui.QApplication.translate("MainWindow", "show percentiles", None, QtGui.QApplication.UnicodeUTF8))
        self.check_plot4.setStatusTip(QtGui.QApplication.translate("MainWindow", "show noise models", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEnable.setTitle(QtGui.QApplication.translate("MainWindow", "Menu", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdd_Console.setText(QtGui.QApplication.translate("MainWindow", "Add Console", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Data.setText(QtGui.QApplication.translate("MainWindow", "Save Data", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLogging_to_File.setText(QtGui.QApplication.translate("MainWindow", "Logging to File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLogging_Window.setText(QtGui.QApplication.translate("MainWindow", "Logging Window", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStart_IPython.setText(QtGui.QApplication.translate("MainWindow", "Start IPython", None, QtGui.QApplication.UnicodeUTF8))

from widgets import MPLWidget
