# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rftool_gui.ui'
#
# Created: Thu Jul  7 17:54:07 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1008, 753)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.canv = MPLWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canv.sizePolicy().hasHeightForWidth())
        self.canv.setSizePolicy(sizePolicy)
        self.canv.setAutoFillBackground(True)
        self.canv.setObjectName(_fromUtf8("canv"))
        self.gridLayout.addWidget(self.canv, 0, 0, 1, 6)
        self.group4 = QtGui.QGroupBox(self.centralwidget)
        self.group4.setMinimumSize(QtCore.QSize(150, 0))
        self.group4.setObjectName(_fromUtf8("group4"))
        self.spin_dec1 = QtGui.QDoubleSpinBox(self.group4)
        self.spin_dec1.setEnabled(True)
        self.spin_dec1.setGeometry(QtCore.QRect(10, 30, 72, 26))
        self.spin_dec1.setWrapping(False)
        self.spin_dec1.setDecimals(9)
        self.spin_dec1.setMinimum(0.0)
        self.spin_dec1.setMaximum(1.0)
        self.spin_dec1.setSingleStep(0.01)
        self.spin_dec1.setProperty(_fromUtf8("value"), 0.005)
        self.spin_dec1.setObjectName(_fromUtf8("spin_dec1"))
        self.spin_dec2 = QtGui.QDoubleSpinBox(self.group4)
        self.spin_dec2.setEnabled(True)
        self.spin_dec2.setGeometry(QtCore.QRect(10, 50, 61, 26))
        self.spin_dec2.setWrapping(False)
        self.spin_dec2.setDecimals(1)
        self.spin_dec2.setMinimum(0.0)
        self.spin_dec2.setMaximum(100.0)
        self.spin_dec2.setSingleStep(1.0)
        self.spin_dec2.setProperty(_fromUtf8("value"), 10.0)
        self.spin_dec2.setObjectName(_fromUtf8("spin_dec2"))
        self.spin_dec3 = QtGui.QDoubleSpinBox(self.group4)
        self.spin_dec3.setEnabled(True)
        self.spin_dec3.setGeometry(QtCore.QRect(10, 70, 61, 26))
        self.spin_dec3.setWrapping(False)
        self.spin_dec3.setDecimals(1)
        self.spin_dec3.setMinimum(0.0)
        self.spin_dec3.setMaximum(100.0)
        self.spin_dec3.setSingleStep(1.0)
        self.spin_dec3.setProperty(_fromUtf8("value"), 20.0)
        self.spin_dec3.setObjectName(_fromUtf8("spin_dec3"))
        self.spin_win1 = QtGui.QDoubleSpinBox(self.group4)
        self.spin_win1.setEnabled(True)
        self.spin_win1.setGeometry(QtCore.QRect(80, 30, 61, 26))
        self.spin_win1.setWrapping(False)
        self.spin_win1.setDecimals(1)
        self.spin_win1.setMinimum(-100.0)
        self.spin_win1.setMaximum(100.0)
        self.spin_win1.setSingleStep(1.0)
        self.spin_win1.setProperty(_fromUtf8("value"), -10.0)
        self.spin_win1.setObjectName(_fromUtf8("spin_win1"))
        self.spin_win2 = QtGui.QDoubleSpinBox(self.group4)
        self.spin_win2.setEnabled(True)
        self.spin_win2.setGeometry(QtCore.QRect(80, 50, 61, 26))
        self.spin_win2.setWrapping(False)
        self.spin_win2.setDecimals(1)
        self.spin_win2.setMinimum(-100.0)
        self.spin_win2.setMaximum(100.0)
        self.spin_win2.setSingleStep(1.0)
        self.spin_win2.setProperty(_fromUtf8("value"), 30.0)
        self.spin_win2.setObjectName(_fromUtf8("spin_win2"))
        self.spin_win3 = QtGui.QDoubleSpinBox(self.group4)
        self.spin_win3.setEnabled(True)
        self.spin_win3.setGeometry(QtCore.QRect(80, 70, 61, 26))
        self.spin_win3.setWrapping(False)
        self.spin_win3.setDecimals(1)
        self.spin_win3.setMinimum(-100.0)
        self.spin_win3.setMaximum(100.0)
        self.spin_win3.setSingleStep(1.0)
        self.spin_win3.setProperty(_fromUtf8("value"), 5.0)
        self.spin_win3.setObjectName(_fromUtf8("spin_win3"))
        self.gridLayout.addWidget(self.group4, 1, 4, 1, 1)
        self.group2 = QtGui.QGroupBox(self.centralwidget)
        self.group2.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group2.sizePolicy().hasHeightForWidth())
        self.group2.setSizePolicy(sizePolicy)
        self.group2.setMinimumSize(QtCore.QSize(150, 0))
        self.group2.setObjectName(_fromUtf8("group2"))
        self.check_polar = QtGui.QCheckBox(self.group2)
        self.check_polar.setGeometry(QtCore.QRect(10, 50, 21, 23))
        self.check_polar.setWhatsThis(_fromUtf8(""))
        self.check_polar.setText(_fromUtf8(""))
        self.check_polar.setObjectName(_fromUtf8("check_polar"))
        self.check_display1 = QtGui.QCheckBox(self.group2)
        self.check_display1.setEnabled(True)
        self.check_display1.setGeometry(QtCore.QRect(10, 20, 131, 23))
        self.check_display1.setWhatsThis(_fromUtf8(""))
        self.check_display1.setObjectName(_fromUtf8("check_display1"))
        self.spin_rot1 = QtGui.QDoubleSpinBox(self.group2)
        self.spin_rot1.setEnabled(False)
        self.spin_rot1.setGeometry(QtCore.QRect(40, 50, 62, 26))
        self.spin_rot1.setToolTip(_fromUtf8(""))
        self.spin_rot1.setWrapping(False)
        self.spin_rot1.setDecimals(1)
        self.spin_rot1.setMinimum(-100.0)
        self.spin_rot1.setMaximum(100.0)
        self.spin_rot1.setSingleStep(1.0)
        self.spin_rot1.setProperty(_fromUtf8("value"), -5.0)
        self.spin_rot1.setObjectName(_fromUtf8("spin_rot1"))
        self.spin_rot2 = QtGui.QDoubleSpinBox(self.group2)
        self.spin_rot2.setEnabled(False)
        self.spin_rot2.setGeometry(QtCore.QRect(40, 70, 62, 26))
        self.spin_rot2.setToolTip(_fromUtf8(""))
        self.spin_rot2.setWrapping(False)
        self.spin_rot2.setDecimals(1)
        self.spin_rot2.setMinimum(-100.0)
        self.spin_rot2.setMaximum(100.0)
        self.spin_rot2.setSingleStep(1.0)
        self.spin_rot2.setProperty(_fromUtf8("value"), 15.0)
        self.spin_rot2.setObjectName(_fromUtf8("spin_rot2"))
        self.label_3 = QtGui.QLabel(self.group2)
        self.label_3.setGeometry(QtCore.QRect(100, 55, 61, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.group2)
        self.label_4.setGeometry(QtCore.QRect(100, 75, 61, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.group2, 1, 2, 1, 1)
        self.group1 = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group1.sizePolicy().hasHeightForWidth())
        self.group1.setSizePolicy(sizePolicy)
        self.group1.setMinimumSize(QtCore.QSize(150, 0))
        self.group1.setTitle(_fromUtf8(""))
        self.group1.setObjectName(_fromUtf8("group1"))
        self.spin_filter1 = QtGui.QDoubleSpinBox(self.group1)
        self.spin_filter1.setEnabled(True)
        self.spin_filter1.setGeometry(QtCore.QRect(20, 50, 62, 26))
        self.spin_filter1.setWrapping(False)
        self.spin_filter1.setDecimals(3)
        self.spin_filter1.setMaximum(100.0)
        self.spin_filter1.setSingleStep(0.1)
        self.spin_filter1.setProperty(_fromUtf8("value"), 0.5)
        self.spin_filter1.setObjectName(_fromUtf8("spin_filter1"))
        self.spin_filter2 = QtGui.QDoubleSpinBox(self.group1)
        self.spin_filter2.setEnabled(False)
        self.spin_filter2.setGeometry(QtCore.QRect(20, 70, 62, 26))
        self.spin_filter2.setWrapping(False)
        self.spin_filter2.setDecimals(3)
        self.spin_filter2.setMaximum(100.0)
        self.spin_filter2.setSingleStep(1.0)
        self.spin_filter2.setProperty(_fromUtf8("value"), 20.0)
        self.spin_filter2.setObjectName(_fromUtf8("spin_filter2"))
        self.label = QtGui.QLabel(self.group1)
        self.label.setGeometry(QtCore.QRect(80, 50, 61, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.group1)
        self.label_2.setGeometry(QtCore.QRect(80, 70, 61, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.combo_filter = QtGui.QComboBox(self.group1)
        self.combo_filter.setGeometry(QtCore.QRect(26, 30, 51, 26))
        self.combo_filter.setObjectName(_fromUtf8("combo_filter"))
        self.combo_filter.addItem(_fromUtf8(""))
        self.combo_filter.addItem(_fromUtf8(""))
        self.combo_filter.addItem(_fromUtf8(""))
        self.combo_filter.addItem(_fromUtf8(""))
        self.push_update1 = QtGui.QPushButton(self.group1)
        self.push_update1.setGeometry(QtCore.QRect(100, 0, 51, 25))
        self.push_update1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.push_update1.setObjectName(_fromUtf8("push_update1"))
        self.label_11 = QtGui.QLabel(self.group1)
        self.label_11.setGeometry(QtCore.QRect(20, 8, 55, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.group1, 1, 1, 1, 1)
        self.group5 = QtGui.QGroupBox(self.centralwidget)
        self.group5.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group5.sizePolicy().hasHeightForWidth())
        self.group5.setSizePolicy(sizePolicy)
        self.group5.setMinimumSize(QtCore.QSize(160, 0))
        self.group5.setTitle(_fromUtf8(""))
        self.group5.setObjectName(_fromUtf8("group5"))
        self.edit_slice = QtGui.QLineEdit(self.group5)
        self.edit_slice.setGeometry(QtCore.QRect(60, 40, 51, 26))
        self.edit_slice.setObjectName(_fromUtf8("edit_slice"))
        self.label_8 = QtGui.QLabel(self.group5)
        self.label_8.setGeometry(QtCore.QRect(20, 45, 55, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.push_update2 = QtGui.QPushButton(self.group5)
        self.push_update2.setGeometry(QtCore.QRect(110, 0, 51, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_update2.sizePolicy().hasHeightForWidth())
        self.push_update2.setSizePolicy(sizePolicy)
        self.push_update2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.push_update2.setAutoFillBackground(False)
        self.push_update2.setObjectName(_fromUtf8("push_update2"))
        self.check_display2 = QtGui.QCheckBox(self.group5)
        self.check_display2.setGeometry(QtCore.QRect(20, 20, 87, 23))
        self.check_display2.setObjectName(_fromUtf8("check_display2"))
        self.check_save = QtGui.QCheckBox(self.group5)
        self.check_save.setGeometry(QtCore.QRect(20, 0, 87, 23))
        self.check_save.setObjectName(_fromUtf8("check_save"))
        self.push_calc = QtGui.QPushButton(self.group5)
        self.push_calc.setGeometry(QtCore.QRect(110, 70, 51, 25))
        self.push_calc.setObjectName(_fromUtf8("push_calc"))
        self.spin_downsample = QtGui.QDoubleSpinBox(self.group5)
        self.spin_downsample.setEnabled(True)
        self.spin_downsample.setGeometry(QtCore.QRect(20, 70, 62, 26))
        self.spin_downsample.setWrapping(False)
        self.spin_downsample.setDecimals(1)
        self.spin_downsample.setMinimum(0.1)
        self.spin_downsample.setMaximum(200.0)
        self.spin_downsample.setSingleStep(10.0)
        self.spin_downsample.setProperty(_fromUtf8("value"), 20.0)
        self.spin_downsample.setObjectName(_fromUtf8("spin_downsample"))
        self.push_sort = QtGui.QPushButton(self.group5)
        self.push_sort.setGeometry(QtCore.QRect(110, 50, 51, 25))
        self.push_sort.setObjectName(_fromUtf8("push_sort"))
        self.push_select = QtGui.QPushButton(self.group5)
        self.push_select.setGeometry(QtCore.QRect(110, 30, 51, 25))
        self.push_select.setObjectName(_fromUtf8("push_select"))
        self.gridLayout.addWidget(self.group5, 1, 5, 1, 1)
        self.group0 = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group0.sizePolicy().hasHeightForWidth())
        self.group0.setSizePolicy(sizePolicy)
        self.group0.setMinimumSize(QtCore.QSize(150, 100))
        self.group0.setObjectName(_fromUtf8("group0"))
        self.spin_scale1 = QtGui.QDoubleSpinBox(self.group0)
        self.spin_scale1.setEnabled(True)
        self.spin_scale1.setGeometry(QtCore.QRect(10, 30, 62, 26))
        self.spin_scale1.setWrapping(False)
        self.spin_scale1.setDecimals(4)
        self.spin_scale1.setMaximum(100.0)
        self.spin_scale1.setSingleStep(0.0001)
        self.spin_scale1.setProperty(_fromUtf8("value"), 1.0)
        self.spin_scale1.setObjectName(_fromUtf8("spin_scale1"))
        self.spin_scale3 = QtGui.QDoubleSpinBox(self.group0)
        self.spin_scale3.setEnabled(True)
        self.spin_scale3.setGeometry(QtCore.QRect(80, 30, 62, 26))
        self.spin_scale3.setWrapping(False)
        self.spin_scale3.setDecimals(3)
        self.spin_scale3.setMaximum(100.0)
        self.spin_scale3.setSingleStep(0.1)
        self.spin_scale3.setProperty(_fromUtf8("value"), 1.0)
        self.spin_scale3.setObjectName(_fromUtf8("spin_scale3"))
        self.check_display3 = QtGui.QCheckBox(self.group0)
        self.check_display3.setGeometry(QtCore.QRect(40, 60, 21, 23))
        self.check_display3.setText(_fromUtf8(""))
        self.check_display3.setChecked(True)
        self.check_display3.setObjectName(_fromUtf8("check_display3"))
        self.check_display4 = QtGui.QCheckBox(self.group0)
        self.check_display4.setGeometry(QtCore.QRect(70, 60, 21, 23))
        self.check_display4.setText(_fromUtf8(""))
        self.check_display4.setObjectName(_fromUtf8("check_display4"))
        self.gridLayout.addWidget(self.group0, 1, 0, 1, 1)
        self.group3 = QtGui.QGroupBox(self.centralwidget)
        self.group3.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group3.sizePolicy().hasHeightForWidth())
        self.group3.setSizePolicy(sizePolicy)
        self.group3.setMinimumSize(QtCore.QSize(220, 0))
        self.group3.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.group3.setFlat(False)
        self.group3.setCheckable(False)
        self.group3.setObjectName(_fromUtf8("group3"))
        self.check_select1 = QtGui.QCheckBox(self.group3)
        self.check_select1.setGeometry(QtCore.QRect(40, 30, 21, 23))
        self.check_select1.setText(_fromUtf8(""))
        self.check_select1.setChecked(True)
        self.check_select1.setObjectName(_fromUtf8("check_select1"))
        self.check_select2 = QtGui.QCheckBox(self.group3)
        self.check_select2.setGeometry(QtCore.QRect(40, 50, 21, 23))
        self.check_select2.setText(_fromUtf8(""))
        self.check_select2.setChecked(True)
        self.check_select2.setObjectName(_fromUtf8("check_select2"))
        self.spin_select1 = QtGui.QDoubleSpinBox(self.group3)
        self.spin_select1.setEnabled(True)
        self.spin_select1.setGeometry(QtCore.QRect(70, 30, 62, 26))
        self.spin_select1.setWrapping(False)
        self.spin_select1.setDecimals(1)
        self.spin_select1.setMinimum(0.0)
        self.spin_select1.setMaximum(20.0)
        self.spin_select1.setSingleStep(0.1)
        self.spin_select1.setProperty(_fromUtf8("value"), 1.2)
        self.spin_select1.setObjectName(_fromUtf8("spin_select1"))
        self.spin_select2 = QtGui.QDoubleSpinBox(self.group3)
        self.spin_select2.setEnabled(True)
        self.spin_select2.setGeometry(QtCore.QRect(70, 50, 62, 26))
        self.spin_select2.setWrapping(False)
        self.spin_select2.setDecimals(1)
        self.spin_select2.setMinimum(0.0)
        self.spin_select2.setMaximum(20.0)
        self.spin_select2.setSingleStep(0.1)
        self.spin_select2.setProperty(_fromUtf8("value"), 2.0)
        self.spin_select2.setObjectName(_fromUtf8("spin_select2"))
        self.spin_select3 = QtGui.QDoubleSpinBox(self.group3)
        self.spin_select3.setEnabled(True)
        self.spin_select3.setGeometry(QtCore.QRect(70, 70, 62, 26))
        self.spin_select3.setWrapping(False)
        self.spin_select3.setDecimals(1)
        self.spin_select3.setMinimum(0.0)
        self.spin_select3.setMaximum(20.0)
        self.spin_select3.setSingleStep(0.1)
        self.spin_select3.setProperty(_fromUtf8("value"), 1.0)
        self.spin_select3.setObjectName(_fromUtf8("spin_select3"))
        self.push_delete = QtGui.QPushButton(self.group3)
        self.push_delete.setGeometry(QtCore.QRect(170, 0, 51, 25))
        self.push_delete.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.push_delete.setObjectName(_fromUtf8("push_delete"))
        self.check_select3 = QtGui.QCheckBox(self.group3)
        self.check_select3.setGeometry(QtCore.QRect(60, 10, 21, 23))
        self.check_select3.setText(_fromUtf8(""))
        self.check_select3.setObjectName(_fromUtf8("check_select3"))
        self.spin_select4 = QtGui.QDoubleSpinBox(self.group3)
        self.spin_select4.setEnabled(True)
        self.spin_select4.setGeometry(QtCore.QRect(140, 50, 62, 26))
        self.spin_select4.setWrapping(False)
        self.spin_select4.setDecimals(1)
        self.spin_select4.setMinimum(0.5)
        self.spin_select4.setMaximum(20.0)
        self.spin_select4.setSingleStep(0.1)
        self.spin_select4.setProperty(_fromUtf8("value"), 1.5)
        self.spin_select4.setObjectName(_fromUtf8("spin_select4"))
        self.check_select4 = QtGui.QCheckBox(self.group3)
        self.check_select4.setGeometry(QtCore.QRect(140, 70, 21, 23))
        self.check_select4.setChecked(False)
        self.check_select4.setObjectName(_fromUtf8("check_select4"))
        self.check_select5 = QtGui.QCheckBox(self.group3)
        self.check_select5.setGeometry(QtCore.QRect(170, 70, 21, 23))
        self.check_select5.setChecked(True)
        self.check_select5.setObjectName(_fromUtf8("check_select5"))
        self.label_9 = QtGui.QLabel(self.group3)
        self.label_9.setGeometry(QtCore.QRect(10, 55, 16, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.group3)
        self.label_10.setGeometry(QtCore.QRect(10, 35, 31, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_13 = QtGui.QLabel(self.group3)
        self.label_13.setGeometry(QtCore.QRect(10, 15, 55, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.group3, 1, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1008, 22))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuMenu = QtGui.QMenu(self.menuBar)
        self.menuMenu.setObjectName(_fromUtf8("menuMenu"))
        self.menuEnable = QtGui.QMenu(self.menuBar)
        self.menuEnable.setObjectName(_fromUtf8("menuEnable"))
        MainWindow.setMenuBar(self.menuBar)
        self.actionOpen_Data = QtGui.QAction(MainWindow)
        self.actionOpen_Data.setObjectName(_fromUtf8("actionOpen_Data"))
        self.actionSave_RF = QtGui.QAction(MainWindow)
        self.actionSave_RF.setObjectName(_fromUtf8("actionSave_RF"))
        self.actionAdd_Console = QtGui.QAction(MainWindow)
        self.actionAdd_Console.setObjectName(_fromUtf8("actionAdd_Console"))
        self.actionSave_Data = QtGui.QAction(MainWindow)
        self.actionSave_Data.setObjectName(_fromUtf8("actionSave_Data"))
        self.actionFill_Data = QtGui.QAction(MainWindow)
        self.actionFill_Data.setCheckable(False)
        self.actionFill_Data.setObjectName(_fromUtf8("actionFill_Data"))
        self.actionFill_RF = QtGui.QAction(MainWindow)
        self.actionFill_RF.setCheckable(False)
        self.actionFill_RF.setObjectName(_fromUtf8("actionFill_RF"))
        self.actionLogging_to_File = QtGui.QAction(MainWindow)
        self.actionLogging_to_File.setObjectName(_fromUtf8("actionLogging_to_File"))
        self.actionLogging_Window = QtGui.QAction(MainWindow)
        self.actionLogging_Window.setObjectName(_fromUtf8("actionLogging_Window"))
        self.actionStart_IPython = QtGui.QAction(MainWindow)
        self.actionStart_IPython.setObjectName(_fromUtf8("actionStart_IPython"))
        self.menuMenu.addAction(self.actionOpen_Data)
        self.menuMenu.addAction(self.actionSave_Data)
        self.menuMenu.addAction(self.actionSave_RF)
        self.menuEnable.addAction(self.actionFill_Data)
        self.menuEnable.addAction(self.actionFill_RF)
        self.menuEnable.addAction(self.actionAdd_Console)
        self.menuEnable.addAction(self.actionStart_IPython)
        self.menuEnable.addAction(self.actionLogging_to_File)
        self.menuEnable.addAction(self.actionLogging_Window)
        self.menuBar.addAction(self.menuMenu.menuAction())
        self.menuBar.addAction(self.menuEnable.menuAction())

        self.retranslateUi(MainWindow)
        self.combo_filter.setCurrentIndex(1)
        QtCore.QObject.connect(self.check_select1, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.spin_select1.setEnabled)
        QtCore.QObject.connect(self.check_select2, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.spin_select2.setEnabled)
        QtCore.QObject.connect(self.check_select2, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.spin_select3.setEnabled)
        QtCore.QObject.connect(self.check_polar, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.spin_rot1.setEnabled)
        QtCore.QObject.connect(self.check_polar, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.spin_rot2.setEnabled)
        QtCore.QObject.connect(self.check_select2, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.spin_select4.setEnabled)
        QtCore.QObject.connect(self.check_select2, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.check_select4.setEnabled)
        QtCore.QObject.connect(self.check_select2, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.check_select5.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.group4.setTitle(QtGui.QApplication.translate("MainWindow", "Deconvolution", None, QtGui.QApplication.UnicodeUTF8))
        self.spin_dec1.setStatusTip(QtGui.QApplication.translate("MainWindow", "water level in relation to maximum", None, QtGui.QApplication.UnicodeUTF8))
        self.spin_dec2.setStatusTip(QtGui.QApplication.translate("MainWindow", "Frequency of Gauss filter", None, QtGui.QApplication.UnicodeUTF8))
        self.spin_dec3.setStatusTip(QtGui.QApplication.translate("MainWindow", "Time shift", None, QtGui.QApplication.UnicodeUTF8))
        self.spin_win1.setStatusTip(QtGui.QApplication.translate("MainWindow", "Window of Cosine Taper (start, secs relative to ponset)", None, QtGui.QApplication.UnicodeUTF8))
        self.spin_win2.setStatusTip(QtGui.QApplication.translate("MainWindow", "Window of Cosine Taper (end, secs relative to ponset)", None, QtGui.QApplication.UnicodeUTF8))
        self.spin_win3.setStatusTip(QtGui.QApplication.translate("MainWindow", "Window of Cosine Taper (smoothed edges, secs)", None, QtGui.QApplication.UnicodeUTF8))
        self.group2.setTitle(QtGui.QApplication.translate("MainWindow", "Rotation", None, QtGui.QApplication.UnicodeUTF8))
        self.check_polar.setStatusTip(QtGui.QApplication.translate("MainWindow", "use rotation angles determined by polarisaion", None, QtGui.QApplication.UnicodeUTF8))
        self.check_display1.setStatusTip(QtGui.QApplication.translate("MainWindow", "display traces before or after roation", None, QtGui.QApplication.UnicodeUTF8))
        self.check_display1.setText(QtGui.QApplication.translate("MainWindow", "display before rot", None, QtGui.QApplication.UnicodeUTF8))
        self.spin_rot1.setStatusTip(QtGui.QApplication.translate("MainWindow", "Window for determination of polarisation", None, QtGui.QApplication.UnicodeUTF8))
        self.spin_rot2.setStatusTip(QtGui.QApplication.translate("MainWindow", "Window for determination of polarisation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "sec (min)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "sec (max)", None, QtGui.QApplication.UnicodeUTF8))
        self.spin_filter1.setStatusTip(QtGui.QApplication.translate("MainWindow", "everything under this value in sec is filtered out", None, QtGui.QApplication.UnicodeUTF8))
        self.spin_filter2.setStatusTip(QtGui.QApplication.translate("MainWindow", "everything above this value in sec is filtered out", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "sec (min)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "sec (max)", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_filter.setStatusTip(QtGui.QApplication.translate("MainWindow", "Select Filter (frquency domain)", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_filter.setItemText(0, QtGui.QApplication.translate("MainWindow", "no", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_filter.setItemText(1, QtGui.QApplication.translate("MainWindow", "LP", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_filter.setItemText(2, QtGui.QApplication.translate("MainWindow", "HP", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_filter.setItemText(3, QtGui.QApplication.translate("MainWindow", "BP", None, QtGui.QApplication.UnicodeUTF8))
        self.push_update1.setStatusTip(QtGui.QApplication.translate("MainWindow", "Update raw data", None, QtGui.QApplication.UnicodeUTF8))
        self.push_update1.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.edit_slice.setStatusTip(QtGui.QApplication.translate("MainWindow", "Slice for shown traces, use e.g., expression \"5:50\"", None, QtGui.QApplication.UnicodeUTF8))
        self.edit_slice.setText(QtGui.QApplication.translate("MainWindow", ":102", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Traces", None, QtGui.QApplication.UnicodeUTF8))
        self.push_update2.setStatusTip(QtGui.QApplication.translate("MainWindow", "Update all windows", None, QtGui.QApplication.UnicodeUTF8))
        self.push_update2.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.check_display2.setStatusTip(QtGui.QApplication.translate("MainWindow", "display all rf traces", None, QtGui.QApplication.UnicodeUTF8))
        self.check_display2.setText(QtGui.QApplication.translate("MainWindow", "display all", None, QtGui.QApplication.UnicodeUTF8))
        self.check_save.setStatusTip(QtGui.QApplication.translate("MainWindow", "save all traces", None, QtGui.QApplication.UnicodeUTF8))
        self.check_save.setText(QtGui.QApplication.translate("MainWindow", "save all", None, QtGui.QApplication.UnicodeUTF8))
        self.push_calc.setStatusTip(QtGui.QApplication.translate("MainWindow", "Use these settings to calculate multiple files", None, QtGui.QApplication.UnicodeUTF8))
        self.push_calc.setText(QtGui.QApplication.translate("MainWindow", "CALC", None, QtGui.QApplication.UnicodeUTF8))
        self.spin_downsample.setStatusTip(QtGui.QApplication.translate("MainWindow", "downsample new data to this sampling rate", None, QtGui.QApplication.UnicodeUTF8))
        self.push_sort.setText(QtGui.QApplication.translate("MainWindow", "Sort", None, QtGui.QApplication.UnicodeUTF8))
        self.push_select.setStatusTip(QtGui.QApplication.translate("MainWindow", "ultimatively select traces", None, QtGui.QApplication.UnicodeUTF8))
        self.push_select.setText(QtGui.QApplication.translate("MainWindow", "Select", None, QtGui.QApplication.UnicodeUTF8))
        self.group0.setTitle(QtGui.QApplication.translate("MainWindow", "Scale", None, QtGui.QApplication.UnicodeUTF8))
        self.spin_scale1.setStatusTip(QtGui.QApplication.translate("MainWindow", "Scale of raw data", None, QtGui.QApplication.UnicodeUTF8))
        self.spin_scale3.setStatusTip(QtGui.QApplication.translate("MainWindow", "Scale of rf", None, QtGui.QApplication.UnicodeUTF8))
        self.check_display3.setStatusTip(QtGui.QApplication.translate("MainWindow", "sum data over all traces", None, QtGui.QApplication.UnicodeUTF8))
        self.check_display4.setStatusTip(QtGui.QApplication.translate("MainWindow", "sum rf over all traces", None, QtGui.QApplication.UnicodeUTF8))
        self.group3.setTitle(QtGui.QApplication.translate("MainWindow", "Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.check_select1.setStatusTip(QtGui.QApplication.translate("MainWindow", "select criteria for raw data after filtering", None, QtGui.QApplication.UnicodeUTF8))
        self.check_select2.setStatusTip(QtGui.QApplication.translate("MainWindow", "select criteria after deconvolution", None, QtGui.QApplication.UnicodeUTF8))
        self.spin_select1.setStatusTip(QtGui.QApplication.translate("MainWindow", "signal to noise ratio on Z-component", None, QtGui.QApplication.UnicodeUTF8))
        self.spin_select2.setStatusTip(QtGui.QApplication.translate("MainWindow", "signal to noise ratio of L-component", None, QtGui.QApplication.UnicodeUTF8))
        self.spin_select3.setStatusTip(QtGui.QApplication.translate("MainWindow", "signal to noise ratio of Q-component", None, QtGui.QApplication.UnicodeUTF8))
        self.push_delete.setStatusTip(QtGui.QApplication.translate("MainWindow", "Delete selected traces.", None, QtGui.QApplication.UnicodeUTF8))
        self.push_delete.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.check_select3.setStatusTip(QtGui.QApplication.translate("MainWindow", "Select/deselect manually with left/right mouse click on trace", None, QtGui.QApplication.UnicodeUTF8))
        self.spin_select4.setStatusTip(QtGui.QApplication.translate("MainWindow", "maximum of L-peak / maximum behind L-peak", None, QtGui.QApplication.UnicodeUTF8))
        self.check_select4.setStatusTip(QtGui.QApplication.translate("MainWindow", "signal critaeria on Q-component", None, QtGui.QApplication.UnicodeUTF8))
        self.check_select4.setText(QtGui.QApplication.translate("MainWindow", "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
"<ui version=\"4.0\">\n"
" <widget name=\"__qt_fake_top_level\">\n"
"  <widget class=\"QCheckBox\" name=\"check_select2\">\n"
"   <property name=\"geometry\">\n"
"    <rect>\n"
"     <x>10</x>\n"
"     <y>50</y>\n"
"     <width>21</width>\n"
"     <height>23</height>\n"
"    </rect>\n"
"   </property>\n"
"   <property name=\"statusTip\">\n"
"    <string>select after deconvolution</string>\n"
"   </property>\n"
"   <property name=\"text\">\n"
"    <string/>\n"
"   </property>\n"
"   <property name=\"checked\">\n"
"    <bool>true</bool>\n"
"   </property>\n"
"  </widget>\n"
" </widget>\n"
" <resources/>\n"
"</ui>\n"
"", None, QtGui.QApplication.UnicodeUTF8))
        self.check_select5.setStatusTip(QtGui.QApplication.translate("MainWindow", "no broad signals", None, QtGui.QApplication.UnicodeUTF8))
        self.check_select5.setText(QtGui.QApplication.translate("MainWindow", "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
"<ui version=\"4.0\">\n"
" <widget name=\"__qt_fake_top_level\">\n"
"  <widget class=\"QCheckBox\" name=\"check_select2\">\n"
"   <property name=\"geometry\">\n"
"    <rect>\n"
"     <x>10</x>\n"
"     <y>50</y>\n"
"     <width>21</width>\n"
"     <height>23</height>\n"
"    </rect>\n"
"   </property>\n"
"   <property name=\"statusTip\">\n"
"    <string>select after deconvolution</string>\n"
"   </property>\n"
"   <property name=\"text\">\n"
"    <string/>\n"
"   </property>\n"
"   <property name=\"checked\">\n"
"    <bool>true</bool>\n"
"   </property>\n"
"  </widget>\n"
" </widget>\n"
" <resources/>\n"
"</ui>\n"
"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "RF", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Data", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Manual", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMenu.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEnable.setTitle(QtGui.QApplication.translate("MainWindow", "Other", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Data.setText(QtGui.QApplication.translate("MainWindow", "Open Data", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_RF.setText(QtGui.QApplication.translate("MainWindow", "Save RF", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdd_Console.setText(QtGui.QApplication.translate("MainWindow", "Add Console", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Data.setText(QtGui.QApplication.translate("MainWindow", "Save Data", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFill_Data.setText(QtGui.QApplication.translate("MainWindow", "Fill Data", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFill_RF.setText(QtGui.QApplication.translate("MainWindow", "Fill RF", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLogging_to_File.setText(QtGui.QApplication.translate("MainWindow", "Logging to File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLogging_Window.setText(QtGui.QApplication.translate("MainWindow", "Logging Window", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStart_IPython.setText(QtGui.QApplication.translate("MainWindow", "Start IPython", None, QtGui.QApplication.UnicodeUTF8))

from widgets import MPLWidget
